# Generated by @domesystems/templates from template.yaml. Do not edit.
terraform {
  required_providers {
    dome = { source = "dome-systems/dome", version = ">= 0.1.0" }
  }
}

variable "workspace_id" { type = string }

variable "stockfish_mcp_url" {
  type      = string
}

variable "anthropic_api_key" {
  type      = string
  sensitive = true
}

variable "actas_secret" {
  type      = string
  sensitive = true
}

resource "dome_gateway" "chess" {
  workspace_id        = var.workspace_id
  name                = "chess"
  description         = "Chess coach and opponent access to Stockfish and approved model pools."
  is_default          = true
}

resource "dome_gateway_tool" "chess_stockfish_chess_engine" {
  workspace_id        = var.workspace_id
  gateway             = dome_gateway.chess.name
  mcp_connection      = dome_mcp_connection.stockfish.name
  tool                = "chess_engine"
}

resource "dome_gateway_llm_pool" "chess_coach" {
  workspace_id        = var.workspace_id
  gateway             = dome_gateway.chess.name
  llm_pool            = dome_llm_pool.coach.name
}

resource "dome_gateway_llm_pool" "chess_chess_fast" {
  workspace_id        = var.workspace_id
  gateway             = dome_gateway.chess.name
  llm_pool            = dome_llm_pool.chess_fast.name
}

resource "dome_gateway_llm_pool" "chess_chess_balanced" {
  workspace_id        = var.workspace_id
  gateway             = dome_gateway.chess.name
  llm_pool            = dome_llm_pool.chess_balanced.name
}

resource "dome_gateway_llm_pool" "chess_chess_strong" {
  workspace_id        = var.workspace_id
  gateway             = dome_gateway.chess.name
  llm_pool            = dome_llm_pool.chess_strong.name
}

resource "dome_mcp_connection" "stockfish" {
  workspace_id        = var.workspace_id
  name                = "stockfish"
  protocol            = "streamable-http"
  url                 = "var.stockfish_mcp_url"
  auth_method         = "none"
  credential_type     = "none"
}

resource "dome_llm_connection" "sonnet" {
  workspace_id        = var.workspace_id
  name                = "sonnet"
  provider_id         = "anthropic"
  provider_config     = jsonencode({"model":"claude-sonnet-4-6"})
  auth_method         = "api-key"
  credential_type     = "shared"
  managed_header_name = "x-api-key"
  secret_values       = { "x-api-key" = var.anthropic_api_key }
}

resource "dome_llm_pool" "coach" {
  workspace_id        = var.workspace_id
  name                = "coach"
  is_default          = false
}

resource "dome_llm_pool_member" "coach_sonnet" {
  workspace_id        = var.workspace_id
  pool                = dome_llm_pool.coach.name
  llm_connection      = dome_llm_connection.sonnet.name
}

resource "dome_llm_pool" "chess_fast" {
  workspace_id        = var.workspace_id
  name                = "chess-fast"
  is_default          = false
}

resource "dome_llm_pool_member" "chess_fast_sonnet" {
  workspace_id        = var.workspace_id
  pool                = dome_llm_pool.chess_fast.name
  llm_connection      = dome_llm_connection.sonnet.name
}

resource "dome_llm_pool" "chess_balanced" {
  workspace_id        = var.workspace_id
  name                = "chess-balanced"
  is_default          = false
}

resource "dome_llm_pool_member" "chess_balanced_sonnet" {
  workspace_id        = var.workspace_id
  pool                = dome_llm_pool.chess_balanced.name
  llm_connection      = dome_llm_connection.sonnet.name
}

resource "dome_llm_pool" "chess_strong" {
  workspace_id        = var.workspace_id
  name                = "chess-strong"
  is_default          = false
}

resource "dome_llm_pool_member" "chess_strong_sonnet" {
  workspace_id        = var.workspace_id
  pool                = dome_llm_pool.chess_strong.name
  llm_connection      = dome_llm_connection.sonnet.name
}

resource "dome_managed_agent" "chess_coach" {
  workspace_id        = var.workspace_id
  name                = "chess-coach"
  act_as              = { method = "hmac", required = true }
  act_as_hmac_secret  = var.actas_secret
  actas_allowed_subjects = ["alex", "sam"]
  system_prompt       = <<-PROMPT
  You are a patient chess coach. Before recommending a move, analyze the supplied
  position with Stockfish. Explain the idea in language appropriate for the
  player, then give one concrete variation in algebraic notation.

  You provide advice; never make a move for the player.

  PROMPT
  default_model       = dome_llm_pool.coach.name
  gateway             = dome_gateway.chess.name
}

resource "dome_agent_rules_bundle" "chess_coach" {
  workspace_id        = var.workspace_id
  agent               = dome_managed_agent.chess_coach.name
  files = {
    "chess-coach.cedar" = <<-CEDAR
    // Delegated coach: discover the engine, call it, and use only the coaching pool.
    permit(
      principal is Dome::Agent,
      action == Dome::Action::"mcp:discover",
      resource
    );

    permit(
      principal is Dome::Agent,
      action == Dome::Action::"mcp:call",
      resource == Dome::MCPTool::"stockfish/chess_engine"
    );

    permit(
      principal is Dome::Agent,
      action == Dome::Action::"llm:invoke",
      resource is Dome::LLMModel
    ) when {
      resource.pool == "coach"
    };

    CEDAR
  }
}

resource "dome_managed_agent" "opponent_stockfish" {
  workspace_id        = var.workspace_id
  name                = "opponent-stockfish"
  system_prompt       = <<-PROMPT
  You are the standing Black opponent in a chess game. Use Stockfish to analyze
  the position and return exactly one legal move in algebraic notation. Do not
  explain your move unless asked.

  PROMPT
  default_model       = dome_llm_pool.chess_balanced.name
  gateway             = dome_gateway.chess.name
}

resource "dome_agent_rules_bundle" "opponent_stockfish" {
  workspace_id        = var.workspace_id
  agent               = dome_managed_agent.opponent_stockfish.name
  files = {
    "opponent-stockfish.cedar" = <<-CEDAR
    // Standing opponent: discover the engine and choose only an opponent pool.
    permit(
      principal is Dome::Agent,
      action == Dome::Action::"mcp:discover",
      resource
    );

    permit(
      principal is Dome::Agent,
      action == Dome::Action::"mcp:call",
      resource == Dome::MCPTool::"stockfish/chess_engine"
    );

    permit(
      principal is Dome::Agent,
      action == Dome::Action::"llm:invoke",
      resource is Dome::LLMModel
    ) when {
      resource has pool &&
      resource.pool in ["chess-fast", "chess-balanced", "chess-strong"]
    };

    CEDAR
  }
}

resource "dome_quota" "chess_coach_daily_spend" {
  workspace_id        = var.workspace_id
  dimension           = "llm"
  unit                = "dome_usd"
  subject_type        = "agent"
  subject             = dome_managed_agent.chess_coach.name
  scope               = "total"
  window              = "daily"
  limit_amount        = 5000000
  name                = "chess-coach daily spend"
}

resource "dome_quota" "opponent_stockfish_daily_spend" {
  workspace_id        = var.workspace_id
  dimension           = "llm"
  unit                = "dome_usd"
  subject_type        = "agent"
  subject             = dome_managed_agent.opponent_stockfish.name
  scope               = "total"
  window              = "daily"
  limit_amount        = 2000000
  name                = "opponent-stockfish daily spend"
}
