# Generated by @domesystems/templates from template.yaml. Do not edit.
terraform {
  required_providers {
    dome = { source = "dome-systems/dome", version = ">= 0.1.0" }
  }
}

variable "workspace_id" { type = string }

variable "tinyfish_api_key" {
  type      = string
  sensitive = true
}

variable "anthropic_api_key" {
  type      = string
  sensitive = true
}

resource "dome_gateway" "web_research" {
  workspace_id        = var.workspace_id
  name                = "web-research"
  description         = "Read-only TinyFish access for the web researcher."
  is_default          = true
  safe_tool_names     = true
}

resource "dome_gateway_tool" "web_research_tinyfish_search" {
  workspace_id        = var.workspace_id
  gateway             = dome_gateway.web_research.name
  mcp_connection      = dome_mcp_connection.tinyfish.name
  tool                = "search"
}

resource "dome_gateway_tool" "web_research_tinyfish_fetch_content" {
  workspace_id        = var.workspace_id
  gateway             = dome_gateway.web_research.name
  mcp_connection      = dome_mcp_connection.tinyfish.name
  tool                = "fetch_content"
}

resource "dome_gateway_llm_pool" "web_research_researcher_pool" {
  workspace_id        = var.workspace_id
  gateway             = dome_gateway.web_research.name
  llm_pool            = dome_llm_pool.researcher_pool.name
}

resource "dome_mcp_connection" "tinyfish" {
  workspace_id        = var.workspace_id
  name                = "tinyfish"
  protocol            = "streamable-http"
  url                 = "https://agent.tinyfish.ai/mcp"
  auth_method         = "api-key"
  credential_type     = "shared"
  managed_header_name = "Authorization"
  secret_values       = { "Authorization" = var.tinyfish_api_key }
}

resource "dome_llm_connection" "sonnet" {
  workspace_id        = var.workspace_id
  name                = "sonnet"
  provider_id         = "anthropic"
  provider_config     = jsonencode({"model":"claude-sonnet-5"})
  auth_method         = "api-key"
  credential_type     = "shared"
  managed_header_name = "x-api-key"
  secret_values       = { "x-api-key" = var.anthropic_api_key }
}

resource "dome_llm_pool" "researcher_pool" {
  workspace_id        = var.workspace_id
  name                = "researcher-pool"
  is_default          = false
}

resource "dome_llm_pool_member" "researcher_pool_sonnet" {
  workspace_id        = var.workspace_id
  pool                = dome_llm_pool.researcher_pool.name
  llm_connection      = dome_llm_connection.sonnet.name
}

resource "dome_managed_agent" "web_researcher" {
  workspace_id        = var.workspace_id
  name                = "web-researcher"
  metadata            = { "dome.template.name" = "im2nguyen/ai-agent-for-tinyfish", "dome.template.version" = "0.1.0" }
  system_prompt       = <<-PROMPT
  You answer questions using the live web through TinyFish.

  Search for sources relevant to the question, then fetch and read the two or
  three most useful pages. Answer from what you found and name each source with
  its URL. Prefer primary sources such as official documentation, company pages,
  or filings over commentary.

  Say plainly when the sources do not settle the question or disagree. When a
  claim depends on recency, state how current the source appears to be.

  You have read-only research tools. Do not claim to have submitted forms, signed
  in, made purchases, or performed browser automation.

  PROMPT
  default_model       = dome_llm_pool.researcher_pool.name
  gateway             = dome_gateway.web_research.name
}

resource "dome_agent_rules_bundle" "web_researcher" {
  workspace_id        = var.workspace_id
  agent               = dome_managed_agent.web_researcher.name
  files = {
    "researcher.cedar" = <<-CEDAR
    // The managed researcher can discover its gateway and use only TinyFish reads.
    permit ( principal, action == Dome::Action::"mcp:discover", resource );
    permit ( principal, action == Dome::Action::"mcp:call", resource == Dome::MCPTool::"tinyfish/search" );
    permit ( principal, action == Dome::Action::"mcp:call", resource == Dome::MCPTool::"tinyfish/fetch_content" );

    CEDAR
  }
}

resource "dome_quota" "web_researcher_daily_spend" {
  workspace_id        = var.workspace_id
  dimension           = "llm"
  unit                = "dome_usd"
  subject_type        = "agent"
  subject             = dome_managed_agent.web_researcher.name
  scope               = "total"
  window              = "daily"
  limit_amount        = 5000000
  name                = "web-researcher daily spend"
}
