# Generated by @domesystems/templates from template.yaml. Do not edit.
terraform {
  required_providers {
    dome = { source = "dome-systems/dome", version = ">= 0.1.0" }
  }
}

variable "workspace_id" { type = string }

variable "anthropic_api_key" {
  type      = string
  sensitive = true
}

resource "dome_gateway" "motivational_haiku" {
  workspace_id        = var.workspace_id
  name                = "motivational-haiku"
  description         = "Gateway for the Motivational Haiku template."
  is_default          = true
}

resource "dome_gateway_llm_pool" "motivational_haiku_motivational_haiku_pool" {
  workspace_id        = var.workspace_id
  gateway             = dome_gateway.motivational_haiku.name
  llm_pool            = dome_llm_pool.motivational_haiku_pool.name
}

resource "dome_llm_connection" "haiku" {
  workspace_id        = var.workspace_id
  name                = "haiku"
  provider_id         = "anthropic"
  provider_config     = jsonencode({"model":"claude-haiku-4-5-20251001"})
  auth_method         = "api-key"
  credential_type     = "shared"
  managed_header_name = "x-api-key"
  secret_values       = { "x-api-key" = var.anthropic_api_key }
}

resource "dome_llm_pool" "motivational_haiku_pool" {
  workspace_id        = var.workspace_id
  name                = "motivational-haiku-pool"
  is_default          = false
}

resource "dome_llm_pool_member" "motivational_haiku_pool_haiku" {
  workspace_id        = var.workspace_id
  pool                = dome_llm_pool.motivational_haiku_pool.name
  llm_connection      = dome_llm_connection.haiku.name
}

resource "dome_managed_agent" "motivational_haiku" {
  workspace_id        = var.workspace_id
  name                = "motivational-haiku"
  system_prompt       = <<-PROMPT
  You write a single original motivational haiku in response to the user's
  challenge, intention, or moment of doubt.

  Your response must contain exactly three lines with a 5–7–5 syllable pattern.
  Make it encouraging, concrete, and kind. Do not add a title, explanation,
  quotation marks, or any text before or after the haiku.

  PROMPT
  default_model       = dome_llm_pool.motivational_haiku_pool.name
  gateway             = dome_gateway.motivational_haiku.name
}
