# Generated by @domesystems/templates from template.yaml. Do not edit.
terraform {
  required_providers {
    dome = { source = "dome-systems/dome", version = ">= 0.1.0" }
  }
}

variable "workspace_id" { type = string }

variable "anthropic_api_key" {
  type      = string
  sensitive = true
}

resource "dome_gateway" "hello_dome" {
  workspace_id        = var.workspace_id
  name                = "hello-dome"
  description         = "Gateway for the Hello Dome template."
  is_default          = false
}

resource "dome_gateway_llm_pool" "hello_dome_hello_dome_pool" {
  workspace_id        = var.workspace_id
  gateway             = dome_gateway.hello_dome.name
  llm_pool            = dome_llm_pool.hello_dome_pool.name
}

resource "dome_llm_connection" "haiku" {
  workspace_id        = var.workspace_id
  name                = "haiku"
  provider_id         = "anthropic"
  provider_config     = jsonencode({"model":"claude-haiku-4-5-20251001"})
  auth_method         = "api-key"
  credential_type     = "shared"
  managed_header_name = "x-api-key"
  secret_values       = { "x-api-key" = var.anthropic_api_key }
}

resource "dome_llm_pool" "hello_dome_pool" {
  workspace_id        = var.workspace_id
  name                = "hello-dome-pool"
  is_default          = false
}

resource "dome_llm_pool_member" "hello_dome_pool_haiku" {
  workspace_id        = var.workspace_id
  pool                = dome_llm_pool.hello_dome_pool.name
  llm_connection      = dome_llm_connection.haiku.name
}

resource "dome_managed_agent" "hello_dome" {
  workspace_id        = var.workspace_id
  name                = "hello-dome"
  allowed_gateways    = [dome_gateway.hello_dome.name]
  system_prompt       = <<-PROMPT
  You are Hello Dome, a concise and helpful assistant who speaks with a warm,
  natural Irish English voice. Use Irish phrasing and expressions sparingly and
  authentically, while keeping every response clear and easy to understand.

  Answer the user directly. If a request needs external data or an action you
  cannot perform, say so plainly instead of inventing a result.

  PROMPT
  default_model       = dome_llm_pool.hello_dome_pool.name
  trigger_config      = jsonencode({"manual":{"enabled":true}})
}
